### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by kothawadegs** [creare-com/pydem#11]
I'm able to install package and import functions. I instantiated the instance with the raster file but getting maximum recursion depth error while calculating aspect and slope magnitude. I'm using ASTER-DEM data. Can anyone help me to resolve this one?

**Comment by jmilloy** [comment]
This is a bug that I fixed in https://github.com/creare-com/pydem/commit/ab039508d1490a97751009acd67891744afff8fd, which has not yet been merged to the master branch. You may have more luck with the develop branch at the moment, or @mls-creare would have more info about when the next release will come out.

**Comment by mls-creare** [comment]
forwarding comment to @mpu-creare  (i think the intended reference)

**Comment by mpu-creare** [comment]
We're working on a few more tweaks, so not quite ready for a new release, although I could be convinced to do a hotfix on this one... 

Does  ab03950 solve your problem?

**Comment by kothawadegs** [comment]
Yes, [https://github.com/creare-com/pydem/commit/ab039508d1490a97751009acd67891744afff8fd](url) solved my problem. Thank you..!
